<div class="outer">
  <a href="add">Add New User</a>
<div class="inner bg-light lter">
<div class="row">
  <!-- .col-lg-6 -->
    <div class="col-lg-12">
      <div class="box">
        <header>
          <h5>Default styles</h5>
          <div class="toolbar">
            <div class="btn-group">
              <a class="btn btn-sm btn-default minimize-box" data-toggle="collapse" href="#defaultTable">
                <i class="fa fa-angle-up"></i>
              </a> 
              <a class="btn btn-danger btn-sm close-box">
                <i class="fa fa-times"></i>
              </a> 
            </div>
          </div>
        </header>
      <div class="body collapse in" id="defaultTable">
        <table class="table responsive-table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Address</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          <?php $i=1;foreach ($user as $u) : ?>
            <tr>
              <td><?php echo $i;?></td>
              <td><?php echo $this->escapeHtml($u->name);?></td>
              <td><?php echo $this->escapeHtml($u->address);?></td>
              <td>
                <?php 
                  if($u->status)
                    echo "Active";
                  else
                    echo "DeActive";
                ?>
              </td>
              <td>
                <a href="<?php echo $this->url('admin',
                    array('action'=>'edit', 'id' => $u->id));?>">Edit</a>
                &nbsp;
                <a href="<?php echo $this->url('admin',
                    array('action'=>'delete', 'id' => $u->id));?>">Delete</a>
              </td>
            </tr>
          <?php $i++;endforeach; ?>  
            
          </tbody>
        </table>
      </div>
    </div>
  </div><!-- /.col-lg-6 -->
</div>
</div>
</div>