<div class="inner bg-light lter">
  <a href="pages/add">Add New Page</a>
  <!--BEGIN INPUT TEXT FIELDS-->
  <div class="row">
    <div class="col-lg-10">
      <div class="box dark">
        <header>
          <div class="icons">
            <i class="fa fa-edit"></i>
          </div>
          <h5>Add Content</h5>
          <!-- .toolbar -->
          <div class="toolbar">
            <nav style="padding: 8px;">
              <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                <i class="fa fa-minus"></i>
              </a> 
              <a href="javascript:;" class="btn btn-default btn-xs full-box">
                <i class="fa fa-expand"></i>
              </a> 
              <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                <i class="fa fa-times"></i>
              </a> 
            </nav>
          </div><!-- /.toolbar -->
        </header>
      <div id="div-1" class="body">
        <?php 
          $form->setAttribute('action', $this->url('pages', array('action' => 'edit','id'=> $this->id,))); 
          $form->setAttribute('class', 'form-horizontal');
          $form->prepare();
          echo $this->form()->openTag($form);
          echo $this->formElement($form->get('id'));
        ?>
        <div class="form-group">
          <label for="text4" class="control-label col-lg-4">Page Name</label>
          <div class="col-lg-4">
            <?php echo $this->formRow($form->get('page_id')); ?>
             
          </div>
        </div><!-- /.form-group -->
        
        <div class="form-group">
          <label for="text4" class="control-label col-lg-4">Content</label>
          <div class="col-lg-8">
            <?php echo $this->formRow($form->get('content'));  ?>
            <script type="text/javascript">
              CKEDITOR.replace( 'content1234' );
            </script>
          </div>
        </div><!-- /.form-group -->

        <div class="form-group">
          <label for="text4" class="control-label col-lg-4">Slug</label>
          <div class="col-lg-4">
            <?php echo $this->formRow($form->get('slug')); ?>
          </div>
        </div><!-- /.form-group -->

        <div class="form-group">
         <div class="col-lg-4">
          <?php echo $this->formElement($form->get('submit')); ?>
         </div>
        </div><!-- /.form-group -->
        <?php echo $this->form()->closeTag();?>
      </div>
    </div>
  </div>
</div><!-- /.row -->
</div><!-- /.inner -->
      