<div class="inner bg-light lter">
<a href="<?php $a="alaa"; echo $this->basePath("css/base.css");?>">google</a>
            <!--BEGIN INPUT TEXT FIELDS-->
            <div class="row">
              <div class="col-lg-10">
                <div class="box dark">
                  <header>
                    <div class="icons">
                      <i class="fa fa-edit"></i>
                    </div>
                    <h5>Add Content</h5>

                    <!-- .toolbar -->
                    <div class="toolbar">
                      <nav style="padding: 8px;">
                        <a href="javascript:;" class="btn btn-default btn-xs collapse-box">
                          <i class="fa fa-minus"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-default btn-xs full-box">
                          <i class="fa fa-expand"></i>
                        </a> 
                        <a href="javascript:;" class="btn btn-danger btn-xs close-box">
                          <i class="fa fa-times"></i>
                        </a> 
                      </nav>
                    </div><!-- /.toolbar -->
                  </header>
                  <div id="div-1" class="body">

                    <?php 
                      $form->setAttribute('action', $this->url('pages', array('action' => 'index'))); 
                      $form->setAttribute('class', 'form-horizontal');
                      $form->prepare();
                      echo $this->form()->openTag($form);
                      echo $this->formElement($form->get('id'));
                    ?>
                      <div class="form-group">
                        <label for="text1" class="control-label col-lg-4">Label</label>
                        <div class="col-lg-8">
                          <?php echo $this->formElement($form->get('label')); ?>
                          <span id="label" class="help-block"><?php echo $this->formElementerrors($form->get('label'));?></span>
                        </div>
                      </div><!-- /.form-group -->

                      <div class="form-group">
                        <label for="text4" class="control-label col-lg-4">Content</label>
                        <div class="col-lg-8">
                           <?php echo $this->formElement($form->get('content')); ?>
<script type="text/javascript">
CKEDITOR.replace( 'content1234' );
//{
//filebrowserBrowseUrl:"<?php echo $this->basePath('/includes/ckfinder/ckfinder.html?Type=Files');?>",
//filebrowserImageBrowseUrl:"<?php echo $this->basePath('/includes/ckfinder/ckfinder.html?Type=Images');?>",
//filebrowserFlashBrowseUrl:"<?php echo $this->basePath('/includes/ckfinder/ckfinder.html?Type=Flash');?>",
//filebrowserUploadUrl:"<?php echo $this->basePath('includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files');?>",
//filebrowserImageUploadUrl:"<?php echo $this->basePath('includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images');?>",
//filebrowserFlashUploadUrl:"<?php echo $this->basePath('includes/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash');?>"
//});
</script>
<script type="text/javascript">
  //CKEDITOR.replace( 'content1234' );
</script>

                           <span id="content" class="help-block"><?php echo $this->formElementerrors($form->get('content'));?></span>
                        </div>
                        	
                      </div><!-- /.form-group -->

                      <div class="form-group">
                        <label for="text4" class="control-label col-lg-4">Page</label>
                        <div class="col-lg-4">
                          <?php echo $this->formElement($form->get('page_id')); ?>
                        </div>
                      </div><!-- /.form-group -->

                      <div class="form-group">
                        <label for="text4" class="control-label col-lg-4">Slug</label>
                        <div class="col-lg-4">
                          <?php echo $this->formElement($form->get('slug')); ?>
                           <span id="slug" class="help-block"><?php echo $this->formElementerrors($form->get('slug'));?></span>
                        </div>
                      </div><!-- /.form-group -->

                      <div class="form-group">
                       <div class="col-lg-4">
                        <?php echo $this->formElement($form->get('submit')); ?>
                      </div>
                      </div><!-- /.form-group -->
                    <?php echo $this->form()->closeTag();?>
                  
                  </div>
                </div>
              </div>

          
             
            </div><!-- /.row -->
          </div><!-- /.inner -->
      