   <script type="text/javascript">
    $(document).ready(function(){
      var page_id;   
      $(".link").click(function() {
          page_id=$(this).attr('data-id');
          $("#page_id").val(page_id);
          //alert($(this).attr('data-id'));
      });
      $( ".confirm" ).click(function() {
        confirm_result=$(this).val();
        if(confirm_result=="yes")
          $("#delete_form").submit();
        else
          $( "#close" ).trigger( "click" );
      });
    });
   </script>
    <div class="bg-dark dk" id="wrap">
      <div id="top">

      <div id="content">
        <div class="outer">
          <div class="inner bg-light lter">

            <!--Begin Datatables-->
            <div class="row">
              <div class="col-lg-12">
                <div class="box">
                  <header>
                    <div class="icons">
                      <i class="fa fa-table"></i>
                    </div>
                    <h5>Dynamic Table</h5>
                  </header>
                  <?php echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));?>
                  <div id="collapse4" class="body">
                    <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                      <thead>
                        <tr>
                          <th>S.NO</th>
                          <th>Slug</th>
                          <th>Page Name</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      <?php $i=1;foreach ($pages as $page) : ?>
                        <tr>
                          <td><?php echo $i;?></td>
                          <td><?php echo $this->escapeHtml($page['slug']);?></td>
                          <td><?php echo $this->escapeHtml($page['page_name']);?></td>
                          <td>
                            <a href="<?php echo $this->url('pages',
                              array('action'=>'edit', 'id' => $page['id']));?>">Edit</a>
                            <a href="#link1" title="title1" class="link" data-toggle="modal" data-id="<?php echo $page['id'];?>">Delete</a>
                          </td>
                        </tr>
                      <?php $i++;endforeach; ?>  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div><!-- /.row -->
<!-- popup start-->
<div id="link1" class="modal fade" >
  <div class="modal-dialog" >
    <div class="modal-content">
      <button id="close" class="close" aria-hidden="true" data-dismiss="modal" type="button">x</button>
      <form id="delete_form" action="pages/delete" method="post">
      <table align="center" cellpadding="5" cellspacing="5">
        <tr>
          <td>
            <h4>Are you sure ?</h4>
          </td>
        </tr>
        <tr>
          <td>
            <input type="hidden" name="page_id" id="page_id">
            <input type="button" class="confirm" name="yes" value="yes"/>
            <input type="button" class="confirm" name="no" value="no"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>
</div>
<!-- popup end-->

   