    <div class="bg-dark dk" id="wrap">
      <div id="top">

      <div id="content">
        <div class="outer">
          <div class="inner bg-light lter">

            <!--Begin Datatables-->
            <div class="row">
              <div class="col-lg-12">
                <div class="box">
                  <header>
                    <div class="icons">
                      <i class="fa fa-table"></i>
                    </div>
                    <h5>Dynamic Table</h5>
                  </header>
                  <div id="collapse4" class="body">
                    <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                      <thead>
                        <tr>
                          <th>S.NO</th>
                          <th>Slug</th>
                          <th>Page Name</th>
                          <th>Action</th>
                        </tr>
                      </thead>
                      <tbody>
                      <?php $i=1;foreach ($pages as $page) : ?>
                        <tr>
                          <td><?php echo $i;?></td>
                          <td><?php echo $this->escapeHtml($page['slug']);?></td>
                          <td><?php echo $this->escapeHtml($page['page_name']);?></td>
                          <td>
                            <a href="<?php echo $this->url('pages',
                              array('action'=>'edit', 'id' => $page['id']));?>">Edit</a>
                            <a href="<?php echo $this->url('pages',
                              array('action'=>'delete', 'id' => $page['id']));?>">Delete</a>
                          </td>
                        </tr>
                      <?php $i++;endforeach; ?>  
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div><!-- /.row -->

   